<a href="https://colab.research.google.com/github/victor-maciel/tabd-unifacisa/blob/master/movies_analise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [9]:
uri='https://raw.githubusercontent.com/DWA-GIT/TESI-UNIFACISA/master/movies_multilinear_reg.csv'
movies = pd.read_csv(uri)
movies.head(5)

movieId                              Titulo  ...  Investimento   Bilheteria
0        1                    Toy Story (1995)  ...     11.048216  5623234.602
1        2                      Jumanji (1995)  ...     14.927678  5714951.757
2        3             Grumpier Old Men (1995)  ...     27.114597  9524339.124
3        4            Waiting to Exhale (1995)  ...      4.994242  6331568.779
4        5  Father of the Bride Part II (1995)  ...     19.142246  6409617.277

[5 rows x 18 columns]

In [11]:
movies.tail(10)

movieId  ...    Bilheteria
9115   161830  ...  6.093774e+06
9116   161918  ...  6.355193e+06
9117   161944  ...  4.087979e+06
9118   162376  ...  7.758407e+06
9119   162542  ...  6.833359e+06
9120   162672  ...  6.318999e+06
9121   163056  ...  5.300340e+06
9122   163949  ...  6.945211e+06
9123   164977  ...  6.459004e+06
9124   164979  ...  1.063624e+07

[10 rows x 18 columns]

In [13]:
movies.shape

(9125, 18)

In [18]:
filmes_independente = movies[movies.columns[2:17]]
type(filmes_independente)


pandas.core.frame.DataFrame

In [0]:
filmes_dependente = movies[movies.columns[17:]]

In [0]:
train, teste, train_bilheteria, test_bilheteria = train_test_split(filmes_independente, filmes_dependente)

In [26]:
train.head(3)

Documentary  Sci-Fi  Mystery  ...  Adventure     Duracao  Investimento
8467            0       0        0  ...          0  128.912801      3.576528
6734            0       0        0  ...          0  119.397001      4.758529
4921            0       0        0  ...          0   93.103625      6.305959

[3 rows x 15 columns]

In [27]:
train.shape

(6843, 15)

In [28]:
teste.shape

(2282, 15)

In [30]:
percentual = teste.shape[0] / movies.shape[0]
percentual

0.2500821917808219

In [32]:
modelo = LinearRegression()
modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
modelo.fit(train, train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
modelo.predict([[0,0,0,0,0,0,0,0,1,0,0,0,0,110.023572,19.142246]])

array([[6958661.00218461]])

In [46]:
acuracia = modelo.score(train,train_bilheteria)
acuracia

0.8295560416558525

In [0]:
train, teste, train_bilheteria, test_bilheteria = train_test_split(filmes_independente, filmes_dependente, test_size=0.3)

In [55]:
modelo_30 = LinearRegression()
modelo_30.fit(train, train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
acuracia_treino = modelo.score(train,train_bilheteria)
acuracia_treino

0.828095692161202

In [64]:
modelo.predict([[0,0,0,0,0,0,0,0,1,0,0,0,0,110.023572,19.142246]])

array([[6958661.00218461]])

In [66]:
zootopia = [0,0,0,0,0,0,0,0,1,1,1,0,1,145.5170642,3.451632127]
planeta_macaco = [0,1,0,0,0,0,0,0,0,0,0,0,0,150,5]
modelo_30.predict([zootopia])

array([[6965399.1183572]])

In [67]:
modelo_30.predict([planeta_macaco])

array([[7400719.2021343]])